[build]
  command = "gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[[headers]]
  for = "/content/images/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
    Netlify-Headers = "netlify headers set"
    X-Insane = "true"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
    Netlify-Headers = "netlify headers set"
    X-Insane = "true"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
    Netlify-Headers = "netlify headers set"
    X-Insane = "true"
