---
# A Kubernetes Service is an abstraction which defines a logical set of Pods and
# a policy by which to access them - sometimes called a micro-service. The set of Pods
# targeted by a Service is (usually) determined by a Label Selector.
# https://kubernetes.io/docs/concepts/services-networking/service/
kind: Service
apiVersion: v1
metadata:
  name: ghost
spec:
  type: LoadBalancer
  selector:
    app: ghost
  ports:
    - name: ghost-backend
      protocol: TCP
      port: 80
      targetPort: 2368
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:alpine
        ports:
          # Ghost by default listens on 2368.
        - containerPort: 2368
          protocol: TCP
        env:
          - name: url
            value: http://cms.callbackinsanity.com
        volumeMounts:
        - mountPath: "/var/lib/ghost/content"
          name: nfs-volume
      volumes:
        - name: nfs-volume
          nfs:
            server: 10.245.170.168
            path: /
