apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-service
spec:
  selector:
    role: nfs
  ports:
    - name: tcp-2049
      port: 2049
      protocol: TCP
    - name: udp-111
      port: 111
      protocol: UDP
---
kind: Pod
apiVersion: v1
metadata:
  name: nfs-server
  labels:
    role: nfs
spec:
  containers:
    - name: nfs-server
      image: itsthenetwork/nfs-server-alpine
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /nfs
          name: do-nfs-share
      env:
        - name: SHARED_DIRECTORY
          value: /nfs
  volumes:
    - name: do-nfs-share
      persistentVolumeClaim:
        claimName: ghost-pvc
